#pragma once
#include "PRMLUtil.h"
#include "SimpleGrid.h"

#include "Function/CubicFunction.h"
#include "Function/LinearFunction.h"
#include "Function/SinFunction.h"
#include "Function/ToyCubicFunction.h"
#include "Function/ToyLinearFunction.h"
#include "Function/ToyNormalFunction.h"
#include "Function/ToySinFunction.h"
#include "Function/Distribution/BernoulliPdfFunction.h"
#include "Function/Distribution/BetaPdfFunction.h"
#include "Function/Distribution/CategoricalPdfFunction.h"
#include "Function/Distribution/DirichletPdfFunction.h"
#include "Function/Distribution/GammaPdfFunction.h"
#include "Function/Distribution/GaussianPdfFunction.h"
#include "Function/Distribution/MultiVariateGaussianPdfFunction.h"
#include "Function/Distribution/StudentsTPdfFunction.h"
#include "Function/Distribution/UniformPdfFunction.h"

#include "Preprocess/GaussianFeature.h"
#include "Preprocess/LabelTransformer.h"
#include "Preprocess/PolynomialFeature.h"
#include "Preprocess/SigmoidalFeature.h"

#include "Linear/BayesianLogisticRegression.h"
#include "Linear/BayesianRegression.h"
#include "Linear/EmpiricalBayesRegression.h"
#include "Linear/FishersLinearDiscriminant.h"
#include "Linear/LeastSquaresClassifier.h"
#include "Linear/LinearRegression.h"
#include "Linear/LogisticRegression.h"
#include "Linear/RidgeRegression.h"
#include "Linear/SoftmaxRegression.h"
